name: normalize-path
description: 'Removes the relative part of a path (e.g. "./my-directory/abc" becomes "my-directory/abc").'
inputs:
  path:
    description: 'The path to be normalized'
    required: true
outputs:
  path:
    description: 'The normalized path'
    value: ${{ steps.normalize-path.outputs.path }}
runs:
  using: 'composite'
  steps:
  - name: Normalize path
    id: normalize-path
    shell: bash
    run: |
      echo "::group::Normalize path"
      NORMALIZED_PATH=$(echo ${{ inputs.path }} | tr -d "./")
      echo "normalized path to $NORMALIZED_PATH"
      echo "::set-output name=path::$(echo $NORMALIZED_PATH)"
      echo "::endgroup::"