name: build-workflow-test
description: 'Builds Spritify.Workflow.Test'
inputs:
  dotnet-version:
    description: '.NET Version to use'
    required: true
  build-testFramework-artifact-key:
    description: 'Artifact key of the build-testFramework step'
    required: true
  build-workflow-artifact-key:
    description: 'Artifact key of the build-workflow step'
    required: true
outputs:
  artifact-key:
    description: 'Key to the build artifact'
    value: ${{ steps.build.outputs.artifact-key }}
runs:
  using: 'composite'
  steps:
    - name: Restore Spritify.TestFramework
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.build-testFramework-artifact-key }}
    - name: Restore Spritify.Workflow
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.build-workflow-artifact-key }}
    - name: Build Spritify.Workflow.Test
      id: build
      uses: ./.github/actions/build-dotnet
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        root-directory: ./workflow
        artifact-name: spritify-workflow-test
        test-projects: true