name: publish-api
description: 'Publishes Spritify.Api'
inputs:
  dotnet-version:
    description: '.NET Version to use'
    required: true
outputs:
  artifact-key:
    description: 'Key to the build artifact'
    value: ${{ steps.publish.outputs.artifact-key }}
runs:
  using: 'composite'
  steps:
    - name: Checkout latest version
      uses: actions/checkout@v2
    - name: Publish Spritify.Api
      id: publish
      uses: ${{ github.workspace }}/.github/actions/publish-dotnet
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        root-directory: ./api
        artifact-name: spritify-api