name: build-common
description: 'Builds Spritify.Common'
inputs:
  dotnet-version:
    description: '.NET Version to use'
    required: true
outputs:
  artifact-key:
    description: 'Key to the build artifact'
    value: ${{ steps.build.outputs.key }}
runs:
  using: 'composite'
  steps:
    - name: Build Spritify.Common
      id: build
      uses: ./.github/actions/build-dotnet
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        root-directory: ./common
        artifact-name: spritify-common