name: create-artifact-key
description: 'Creates an artifact key for the given scenario following a standardized format.'
inputs:
  artifact-name:
    description: 'Name of the build artifact'
    required: true
  is-build-artifact:
    description: 'Indicates whether the artifact is the result of a build operation'
    required: false
    default: false
  is-publish-artifact:
    description: 'Indicates whether the artifact is the result of a publish operation'
    required: false
    default: false
outputs:
  key:
    description: 'The artifact key'
    value: ${{ steps.create-artifact-key.outputs.key }}
runs:
  using: 'composite'
  steps:
  - name: Create artifact key
    id: create-artifact-key
    shell: bash
    run: |
      echo "::group::Create artifact key"
      if [ ${{ inputs.is-build-artifact }} == true ];
      then
      ARTIFACT_KEY=$(echo ${{ inputs.artifact-name }}-build-${{ github.sha }});
      elif [ ${{ inputs.is-publish-artifact}} == true ];
      then
      ARTIFACT_KEY=$(echo ${{ inputs.artifact-name }}-${{ github.sha }});
      else
      echo "The artifact to be named needs to be either a build artifact or a publish artifact." 1>&2;
      exit 2;
      fi
      echo "built artifact key with value $ARTIFACT_KEY"
      echo "::set-output name=key::$(echo $ARTIFACT_KEY)"
      echo "::endgroup::"