name: store-cache
description: 'Caches the given files'
inputs:
  artifact-key:
    description: 'Key of the artifact to store'
    required: true
  find-args:
    description: 'Additional, custom args provided to the unix find command for identifying the items to include in the artifact'
    required: false
    default: ''
  preset:
    description: 'A preset for find-args - supported are "dotnet" and "node"'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
  - name: Create cache directory
    shell: bash
    run: |
      mkdir  ~/.artifacts
  - name: Initialize cache
    uses: actions/cache@v2
    with:
      key: ${{ inputs.artifact-key }}
      path: ~/.artifacts
  - name: Copy files to cache
    shell: bash
    run: |
      echo "::group::Prepare regex"
      if [ ${{ inputs.preset }} == "dotnet" ];
      then
      echo "Mode: dotnet";
      ARGS="-regex ".*/\(bin\|obj\)$"";
      elif [ ${{ inputs.preset }} == "node" ];
      then
      echo "Mode: node";
      ARGS="! -regex ".*/node_modules/.*" -regex ".*/\dist$"";
      else
      echo "Mode: custom arguments";
      ARGS=${{ inputs.find-args }};
      fi
      echo "::endgroup::"
      find ${{ github.workspace }} $ARGS | xargs -I {} cp -r --parents {}  ~/.artifacts