name: store-cache
description: 'Caches the given files'
inputs:
  artifact-key:
    description: 'Key of the artifact to store'
    required: true
  artifact-mode:
    description: 'Defines which items to include in the artifact - supported are "dotnet" and "node"'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Create cache directory
    shell: bash
    run: |
      mkdir  ~/.artifacts
  - name: Initialize cache
    uses: actions/cache@v2
    with:
      key: ${{ inputs.artifact-key }}
      path: ~/.artifacts
  - name: Copy files to cache
    shell: bash
    run: |
      echo "::group::Look for artifact items"
      if [ ${{ inputs.artifact-mode }} == "dotnet" ];
      then
      echo "Mode: dotnet";
      ARGS="-regex \".*/\(bin\|obj\)$\"";
      elif [ ${{ inputs.artifact-mode }} == "node" ];
      then
      echo "Mode: node";
      ARGS="! -regex \".*/node_modules/.*\" -regex \".*/\dist$\"";
      else
      echo "Unknown mode: ${{ inputs.artifact-mode }}.";
      exit 1;
      fi
      echo "::endgroup::"
      eval "find ${{ github.workspace }} $ARGS" | xargs -I {} cp -r --parents {}  ~/.artifacts