name: publish-testResults
description: 'Publishes test results'
inputs:
  test-workflow-artifact-key:
    description: 'Artifact key of the test-workflow step'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Restore Spritify.Workflow.Test results
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.test-workflow-artifact-key }}
        path : .
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: ./**/*.trx
        reporter: dotnet-trx