name: restore-cache
description: 'Restores the files cached under the given artifact name'
inputs:
  artifact-key:
    description: 'Key of the artifact to restore'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Initialize cache
    uses: actions/cache@v2
    with:
      key: ${{ inputs.artifact-key }}
      path: ~/.artifacts/${{ inputs.artifact-key }}
  - name: Copy files from cache
    shell: bash
    run: |
      cp -r ~/.artifacts/${{ inputs.artifact-key }}/* .
  - name: Debug
    shell: bash
    run: |
      echo "::group::Artifact content"
      find ~/.artifacts
      echo "::endgroup::"
      echo "::group::Workspace content"
      find ${{ github.workspace }}
      echo "::endgroup::"