name: restore-cache
description: 'Restores the files cached under the given artifact name'
inputs:
  artifact-key:
    description: 'Key of the artifact to restore'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Get cache directory
    shell: bash
    run: |
      echo "::save-state name=ARTIFACT_KEY::${{ inputs.artifact-key }}"
  - name: Initialize cache
    uses: actions/cache@v2
    with:
      key: $${{ env.STATE_ARTIFACT_KEY }}
      path: ~/.${{ env.STATE_ARTIFACT_KEY }}
  - name: Copy files from cache
    shell: bash
    run: |
      echo "::group::Copy files from cache"
      cp -r ~/.${{ env.STATE_ARTIFACT_KEY }} ${{ github.workspace }}
      echo "::endgroup::"