name: test-dotnet
description: 'Executes the tests inside the given .NET project(s).'
inputs:
  dotnet-version:
    description: '.NET Version to use'
    required: true
  root-directory:
    description: 'Path to the root directory of the project - all tests of all projects inside this directory are run'
    required: true
  artifact-name:
    description: 'Name of the test report artifact'
    required: true
  test-category:
    description: 'If set to a value, only tests of that category are executed. Otherwise, all tests are run.'
    required: false
    default: ''
outputs:
  artifact-key:
    description: 'Key to the test report artifact'
    value: ${{ steps.artifact-key.outputs.key }}
runs:
  using: 'composite'
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
  - name: Normalize path
    id: normalize-path
    uses: ./.github/actions/normalize-path
    with:
      path: ${{ inputs.root-directory }}
  - name: Create artifact key
    id: artifact-key
    uses: ./.github/actions/create-artifact-key
    with:
      artifact-name: ${{ inputs.artifact-name }}
      is-test-artifact: true
  - name: Find projects to build
    uses: ./.github/actions/find-projects
    id: find-projects
    with:
      root-directory: ${{ inputs.root-directory }}
      project-name-schema: '*.csproj'
      test-projects: true
  - name: Test
    shell: bash
    working-directory: ${{ github.workspace }}/${{ steps.normalize-path.outputs.path }}
    run: |
      echo "::group::Test"
      echo ${{ steps.find-projects.outputs.projects }} | tr " " "\n" | xargs /bin/sh -c 'dotnet test $0 --configuration Release --no-build --verbosity normal --results-directory ~/.test --logger \"trx;LogFileName=$(echo $0 | sed "s/[A-Za-z0-9\/\-\.]*\///g" | sed "s/csproj/trx/")\"'
      echo "::endgroup::"
  - name: Process test results
    uses: dorny/test-reporter@v1
    if: success() || failure()
    with:
      name: Test Report
      path: ~/.test
      reporter: dotnet-trx