name: restoreNugetPackages
description: 'Restores the nuget packages for the given project.'
inputs:
  dotnet-version:
    description: '.NET Version to use'
    required: true
  project-path:
    description: 'Path to the project file to restore (the working-directory of parent actions is ignored)'
    required: true
  nuget-cache:
    description: 'Path to the directory where Nuget packages are stored (absolute)'
    required: true
  nuget-cache-version:
    description: 'Version of the Nuget cache - changing the version allows cache invalidation without making changes to the source code'
    required: false
    default: 1
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-dotnet@v1
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
  - uses: actions/cache@v2
    id: nuget-cache
    with:
      path: ${{ inputs.nuget-cache }}
      key: ${{ runner.os }}-nuget-v${{ inputs.nuget-cache-version }}-${{ hashFiles('**/packages.lock.json') }}
  - name: Analyze Cache
    shell: bash
    run: |
      if [ ${{ steps.nuget-cache.outputs.cache-hit }} == 'true' ];
      then
      echo "Cache OK - restoring package info only";
      else
      echo "Cache Not Found - restoring packages";
      fi
  - name: Restore Nuget Packages
    shell: bash
    run: ${{ inputs.project-path }} | xargs -I{} 'dotnet restore ${{ github.workspace }}/{} --packages ${{ inputs.nuget-cache}} --no-dependencies'