name: publish-node
description: 'Publishes the given Node.js project(s).'
inputs:
  root-directory:
    description: 'Path to the root directory of the project - all projects inside this directory are published'
    required: true
  artifact-name:
    description: 'Name of the build artifact'
    required: true
outputs:
  artifact-key:
    description: 'Key to the build artifact'
    value: ${{ steps.publish-artifact-key.outputs.key }}
runs:
  using: 'composite'
  steps:
  - name: Normalize path
    id: normalize-path
    uses: ./.github/actions/normalize-path
    with:
      path: ${{ inputs.root-directory }}
  - name: Create publish artifact key
    id: publish-artifact-key
    uses: ./.github/actions/create-artifact-key
    with:
      artifact-name: ${{ inputs.artifact-name }}
      is-publish-artifact: true
  - name: Create build artifact key
    id: build-artifact-key
    uses: ./.github/actions/create-artifact-key
    with:
      artifact-name: ${{ inputs.artifact-name }}
      is-build-artifact: true
  - name: Restore build artifact
    uses: actions/download-artifact@v2
    with:
      name: ${{ steps.build-artifact-key.outputs.key }}
  - name: Publish
    shell: bash
    working-directory: ${{ github.workspace }}/${{ steps.normalize-path.outputs.path }}
    run: |
      echo "::group::Publish"
      mkdir ~/.publish/wwwroot
      echo find . -type d -name "dist" | xargs -I {} cp -r {}/*/* ~/.publish/wwwroot
      echo "::endgroup::"
  - name: Archive artifacts
    uses: actions/upload-artifact@v2
    with:
      name: ${{ steps.publish-artifact-key.outputs.key }}
      path: ~/.publish